services:
  app:
    image: mysociety/climate_mrp_polling:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/climate_mrp_polling      
    volumes:
      - ./:/workspaces/climate_mrp_polling/